(function(){
'use strict';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
function localDate(){const d=new Date(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return d.getFullYear()+'-'+m+'-'+day}
const state={company:{name:'BNC AgroCare',details:''},invoice:{number:'',date:localDate(),due:'',customer:'',customerDetails:'',notes:'',preparedBy:''},items:[{name:'',qty:1,price:0}],discount:0,tax:0};
const DRAFTS='bnc-invoice-drafts',DB_VERSION=2;
let db,saveTimer;
let deferredInstall=null;

function updateNetworkState(){const el=$('#networkState');if(!el)return;el.textContent=navigator.onLine?'Online':'Offline';el.title=navigator.onLine?'Connected':'Using local data; network unavailable'}
function setupInstall(){const btn=$('#installBtn');if(!btn)return;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;btn.hidden=false});btn.addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();const choice=await deferredInstall.userChoice;if(choice.outcome==='accepted')btn.hidden=true;deferredInstall=null});window.addEventListener('appinstalled',()=>{btn.hidden=true;toast('BNC Invoice installed')})}

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DRAFTS,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('drafts'))d.createObjectStore('drafts',{keyPath:'id'});if(!d.objectStoreNames.contains('invoices')){const store=d.createObjectStore('invoices',{keyPath:'id'});store.createIndex('updatedAt','updatedAt')}};r.onsuccess=()=>{db=r.result;resolve()};r.onerror=()=>reject(r.error)})}
function saveDraft(){if(!db)return;const data=JSON.parse(JSON.stringify(state));const req=db.transaction('drafts','readwrite').objectStore('drafts').put({id:'current',updatedAt:Date.now(),data});req.onsuccess=()=>$('#saveState').textContent='Saved locally';req.onerror=()=>{ $('#saveState').textContent='Save error';toast('Could not save draft') }}
function scheduleSave(){clearTimeout(saveTimer);$('#saveState').textContent='Saving…';saveTimer=setTimeout(saveDraft,180)}
function money(n){return Number(n||0).toFixed(2)}
function escape(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function readForm(){state.company.name=$('#companyName').value.trim()||'BNC AgroCare';state.company.details=$('#companyDetails').value;state.invoice.number=$('#invoiceNumber').value.trim();state.invoice.date=$('#invoiceDate').value;state.invoice.due=$('#invoiceDue').value;state.invoice.customer=$('#customerName').value.trim();state.invoice.customerDetails=$('#customerDetails').value;state.invoice.notes=$('#notes').value;state.invoice.preparedBy=$('#preparedBy').value.trim();state.discount=Math.max(0,Number($('#discount').value)||0);state.tax=Math.max(0,Number($('#tax').value)||0);state.items=$$('.item-row').map(row=>({name:row.querySelector('.item-name').value.trim(),qty:Math.max(0,Number(row.querySelector('.item-qty').value)||0),price:Math.max(0,Number(row.querySelector('.item-price').value)||0)}))}
function totals(){const subtotal=state.items.reduce((sum,i)=>sum+i.qty*i.price,0),afterDiscount=Math.max(0,subtotal-state.discount),taxValue=afterDiscount*(state.tax/100),grand=afterDiscount+taxValue;return{subtotal,afterDiscount,taxValue,grand}}
function renderItems(){const body=$('#itemRows');body.innerHTML='';state.items.forEach((item,index)=>{const row=document.createElement('div');row.className='item-row';row.innerHTML='<input class="field item-name" placeholder="Item / product"><input class="field item-qty" type="number" min="0" step="0.01" value="'+item.qty+'"><input class="field item-price" type="number" min="0" step="0.01" value="'+item.price+'"><div class="item-total">'+money(item.qty*item.price)+'</div><button class="remove" type="button" title="Remove item" aria-label="Remove item">×</button>';row.querySelectorAll('input').forEach(x=>x.addEventListener('input',()=>{readForm();renderPreview();scheduleSave()}));row.querySelector('.remove').addEventListener('click',()=>{if(state.items.length===1)return;state.items.splice(index,1);renderItems();renderPreview();scheduleSave()});body.appendChild(row)});$('#itemCount').textContent=state.items.length+' item'+(state.items.length===1?'':'s')}
function fillForm(){const i=state.invoice;$('#companyName').value=state.company.name;$('#companyDetails').value=state.company.details;$('#invoiceNumber').value=i.number;$('#invoiceDate').value=i.date;$('#invoiceDue').value=i.due;$('#customerName').value=i.customer;$('#customerDetails').value=i.customerDetails;$('#notes').value=i.notes;$('#preparedBy').value=i.preparedBy;$('#discount').value=state.discount;$('#tax').value=state.tax;renderItems();renderPreview()}
function renderPreview(){readForm();$('.item-row').forEach((row,index)=>{const item=state.items[index];if(item){const total=row.querySelector('.item-total');if(total)total.textContent=money(item.qty*item.price)}});const t=totals();$('#printCompany').textContent=state.company.name;$('#printCompanyDetails').textContent=state.company.details||'Agriculture-focused products & solutions';$('#printInvoiceNo').textContent=state.invoice.number||'DRAFT';$('#printInvoiceDate').textContent=state.invoice.date||'—';$('#printDue').textContent=state.invoice.due||'—';$('#printCustomer').textContent=state.invoice.customer||'Customer / Buyer';$('#printCustomerDetails').textContent=state.invoice.customerDetails||'Customer details';$('#printPrepared').textContent=state.invoice.preparedBy||'—';$('#printNotes').textContent=state.invoice.notes||'No additional notes';const tbody=$('#printRows');tbody.innerHTML='';state.items.forEach(i=>{const tr=document.createElement('tr');tr.innerHTML='<td>'+escape(i.name||'—')+'</td><td>'+escape(i.qty)+'</td><td>'+money(i.price)+'</td><td>'+money(i.qty*i.price)+'</td>';tbody.appendChild(tr)});$('#printSubtotal').textContent=money(t.subtotal);$('#printDiscount').textContent=money(state.discount);$('#printTax').textContent=money(t.taxValue);$('#printGrand').textContent=money(t.grand);$('#liveTotal').textContent=money(t.grand);$('#saveState').textContent='Saved locally';scheduleSave()}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2000)}
function nextInvoiceNumber(){
  const key='bnc-invoice-next-number',current=Math.max(1,Number(localStorage.getItem(key)||1)),next='INV-'+String(current).padStart(4,'0');
  localStorage.setItem(key,String(current+1));
  return next;
}
function syncInvoiceCounter(number){const m=String(number||'').trim().match(/^INV-(\d+)$/i);if(!m)return;const next=Math.max(1,Number(localStorage.getItem('bnc-invoice-next-number')||1)),needed=Number(m[1])+1;if(needed>next)localStorage.setItem('bnc-invoice-next-number',String(needed))}
function ensureInvoiceNumber(){if(!state.invoice.number)state.invoice.number=nextInvoiceNumber();syncInvoiceCounter(state.invoice.number)}
function newInvoice(){const company=Object.assign({},state.company);state.company=company;state.invoice={number:nextInvoiceNumber(),date:localDate(),due:'',customer:'',customerDetails:'',notes:'',preparedBy:''};state.items=[{name:'',qty:1,price:0}];state.discount=0;state.tax=0;fillForm();saveDraft();toast('New invoice · '+state.invoice.number)}
function loadDraft(){return new Promise((resolve,reject)=>{if(!db){resolve(false);return}const req=db.transaction('drafts').objectStore('drafts').get('current');req.onsuccess=()=>{if(req.result&&req.result.data){Object.assign(state,req.result.data);fillForm();toast('Draft loaded');resolve(true)}else resolve(false)};req.onerror=()=>reject(req.error)})}
function saveInvoiceRecord(){readForm();if(!db)return;if(!state.invoice.customer&&!state.items.some(item=>item.name||item.price>0)){toast('Fill the invoice before saving');return}ensureInvoiceNumber();const now=Date.now(),data=JSON.parse(JSON.stringify(state)),id=data.invoice.number||('DRAFT-'+now);const req=db.transaction('invoices','readwrite').objectStore('invoices').put({id,invoiceNumber:data.invoice.number||id,customer:data.invoice.customer||'Customer / Buyer',total:totals().grand,updatedAt:now,data});req.onsuccess=()=>{renderHistory();toast('Invoice saved · '+id)};req.onerror=()=>toast('Could not save invoice')}
function loadInvoiceRecord(id){if(!db)return;const req=db.transaction('invoices').objectStore('invoices').get(id);req.onsuccess=()=>{if(!req.result)return;Object.assign(state,req.result.data);fillForm();$('#saveState').textContent='Loaded from history';toast('Invoice loaded · '+(state.invoice.number||id))}}
function duplicateInvoiceRecord(id){if(!db)return;const req=db.transaction('invoices').objectStore('invoices').get(id);req.onsuccess=()=>{if(!req.result)return;Object.assign(state,JSON.parse(JSON.stringify(req.result.data)));state.invoice.number=nextInvoiceNumber();state.invoice.date=localDate();fillForm();saveDraft();toast('Duplicated as '+state.invoice.number)}}
function deleteInvoiceRecord(id){if(!db)return;if(!confirm('Delete this saved invoice?'))return;const req=db.transaction('invoices','readwrite').objectStore('invoices').delete(id);req.onsuccess=()=>{renderHistory();toast('Invoice removed')}}
function renderHistory(){const list=$('#historyList'),empty=$('#historyEmpty');if(!list||!db)return;const req=db.transaction('invoices').objectStore('invoices').index('updatedAt').openCursor(null,'prev');list.innerHTML='';let count=0;req.onsuccess=()=>{const cursor=req.result;if(!cursor){empty.hidden=count>0;return}const a=cursor.value,counted=++count,row=document.createElement('div');row.className='history-row';row.innerHTML='<div><strong>'+escape(a.invoiceNumber)+'</strong><span>'+escape(a.customer)+' · '+money(a.total)+'</span></div><div class="history-actions"><button class="history-load" type="button">Load</button><button class="history-copy" type="button">Copy</button><button class="history-delete" type="button">×</button></div>';row.querySelector('.history-load').addEventListener('click',()=>loadInvoiceRecord(a.id));row.querySelector('.history-copy').addEventListener('click',()=>duplicateInvoiceRecord(a.id));row.querySelector('.history-delete').addEventListener('click',()=>deleteInvoiceRecord(a.id));list.appendChild(row);cursor.continue()}}
function exportJSON(){readForm();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=(state.invoice.number||'bnc-invoice')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function importJSONData(data){if(!data||typeof data!=='object'||!data.invoice||!Array.isArray(data.items))throw new Error('Invalid invoice JSON');state.company={name:String(data.company?.name||'BNC AgroCare'),details:String(data.company?.details||'')};state.invoice={number:String(data.invoice.number||''),date:String(data.invoice.date||localDate()),due:String(data.invoice.due||''),customer:String(data.invoice.customer||''),customerDetails:String(data.invoice.customerDetails||''),notes:String(data.invoice.notes||''),preparedBy:String(data.invoice.preparedBy||'')};syncInvoiceCounter(state.invoice.number);state.items=data.items.map(i=>({name:String(i?.name||''),qty:Math.max(0,Number(i?.qty)||0),price:Math.max(0,Number(i?.price)||0)}));if(!state.items.length)state.items=[{name:'',qty:1,price:0}];state.discount=Math.max(0,Number(data.discount)||0);state.tax=Math.max(0,Number(data.tax)||0);fillForm();scheduleSave();renderHistory();toast('Invoice JSON imported')}
function importJSONFile(file){file.text().then(text=>{let data;try{data=JSON.parse(text)}catch(e){throw new Error('Invalid JSON file')}importJSONData(data)}).catch(e=>toast(e.message||'Could not import JSON'))}
$('.form-input').forEach(x=>x.addEventListener('input',()=>{renderPreview();scheduleSave()}));$('#importBtn').addEventListener('click',()=>$('#importFile').click());$('#importFile').addEventListener('change',e=>{const file=e.target.files?.[0];if(file)importJSONFile(file);e.target.value=''});$('#addItem').addEventListener('click',()=>{readForm();state.items.push({name:'',qty:1,price:0});renderItems();renderPreview();scheduleSave()});$('#newInvoice').addEventListener('click',newInvoice);$('#saveInvoice').addEventListener('click',saveInvoiceRecord);$('#printBtn').addEventListener('click',()=>{renderPreview();saveInvoiceRecord();const oldTitle=document.title;document.title='BNC Invoice '+(state.invoice.number||'DRAFT');window.print();setTimeout(()=>document.title=oldTitle,1000)});$('#previewBtn').addEventListener('click',()=>{$('.workspace').classList.toggle('mobile-preview');$('#previewBtn').textContent=$('.workspace').classList.contains('mobile-preview')?'Edit':'Preview'});$('#jsonBtn').addEventListener('click',exportJSON);
window.addEventListener('online',updateNetworkState);window.addEventListener('offline',updateNetworkState);window.addEventListener('pagehide',()=>{clearTimeout(saveTimer);saveDraft()});updateNetworkState();setupInstall();
(async()=>{try{await openDB();const loaded=await loadDraft();if(!loaded)fillForm();renderHistory()}catch(e){toast('Local draft storage unavailable');fillForm()}})();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();