(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DB_NAME="bnc-invoice-exact-sheet",DB_VERSION=1;
const state={ref:"X2",invoiceNo:"0002",date:"",repName:"Md Rezaul Karim",repRole:"Officer BNC AGRO CARE Area Manager",repMob:"01718-306103",commission:0,amountWords:"",left:Array.from({length:5},()=>({name:"",pack:"",ctn:"",rate:""})),right:Array.from({length:5},()=>({name:"",pack:"",ctn:"",rate:""}))};
let db=null,timer=null,deferredInstall=null;

function localDate(){const d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}function displayDate(v){const m=String(v||"").match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:String(v||"")}function parseDisplayDate(v){const m=String(v||"").trim().match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:String(v||"").trim()}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function money(v){return num(v).toFixed(2)}
function toast(msg){const e=$("#toast");e.textContent=msg;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),1800)}
function nextNo(){const key="bnc-invoice-next",n=Math.max(3,Math.floor(num(localStorage.getItem(key)||3)));localStorage.setItem(key,String(n+1));return String(n).padStart(4,"0")}
function syncCounter(v){const m=String(v||"").match(/^\d{1,4}$/);if(!m)return;const n=Number(m[0])+1,cur=Math.max(1,Math.floor(num(localStorage.getItem("bnc-invoice-next")||1)));if(n>cur)localStorage.setItem("bnc-invoice-next",String(n))}
function ensureNumber(){if(!state.invoiceNo)state.invoiceNo=nextNo();syncCounter(state.invoiceNo)}
function totals(){const all=[...state.left,...state.right],ctn=all.reduce((s,i)=>s+num(i.ctn),0),leftCtn=state.left.reduce((s,i)=>s+num(i.ctn),0),leftAmount=state.left.reduce((s,i)=>s+num(i.ctn)*num(i.rate),0),rightAmount=state.right.reduce((s,i)=>s+num(i.ctn)*num(i.rate),0),totalTaka=leftAmount+rightAmount,grand=Math.max(0,totalTaka-num(state.commission));return{ctn,leftCtn,leftAmount,rightAmount,totalTaka,grand}}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains("invoices")){const s=d.createObjectStore("invoices",{keyPath:"id"});s.createIndex("updatedAt","updatedAt")};if(!d.objectStoreNames.contains("drafts"))d.createObjectStore("drafts",{keyPath:"id"})};r.onsuccess=()=>{db=r.result;resolve()};r.onerror=()=>reject(r.error)})}
function saveDraft(){if(!db)return;const req=db.transaction("drafts","readwrite").objectStore("drafts").put({id:"current",updatedAt:Date.now(),data:state});req.onsuccess=()=>$("#saveState").textContent="Saved locally";req.onerror=()=>$("#saveState").textContent="Save error"}
function scheduleSave(){clearTimeout(timer);$("#saveState").textContent="Saving…";timer=setTimeout(saveDraft,220)}
function readStateFromEditor(){state.ref=$("#ref").value.trim();state.invoiceNo=$("#invoiceNo").value.trim();state.date=$("#invoiceDate").value;state.repName=$("#repName").value.trim();state.repRole=$("#repRole").value.trim();state.repMob=$("#repMob").value.trim();state.commission=Math.max(0,num($("#commission").value));state.amountWords=$("#amountWords").value;["left","right"].forEach(side=>state[side]=state[side].map((item,i)=>{const q=$(`#${side}Editor .prod-row[data-i="${i}"]`);return{name:q.querySelector(".name").value.trim(),pack:q.querySelector(".pack").value.trim(),ctn:q.querySelector(".ctn").value,rate:q.querySelector(".rate").value}}));ensureNumber()}
function makeProductEditor(side){const host=side==="left"?$("#leftEditor"):$("#rightEditor");host.innerHTML='<div class="prod-head"><span>SL</span><span>Products</span><span>Pack</span><span>Ctn</span><span>Rate / Ctn</span></div>'+state[side].map((it,i)=>'<div class="prod-row" data-i="'+i+'"><span class="prod-num">'+(i+1)+'</span><input class="field name" value="'+esc(it.name)+'" placeholder="Product"><input class="field pack" value="'+esc(it.pack)+'" placeholder="Pack"><input class="field ctn" type="number" min="0" step="0.01" value="'+esc(it.ctn)+'"><input class="field rate" type="number" min="0" step="0.01" value="'+esc(it.rate)+'"></div>').join("");$$('#'+side+'Editor .field').forEach(e=>e.addEventListener("input",()=>{syncAll(true)}))}
function esc(v){return String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function buildRows(side){const host=side==="left"?$("#leftRows"):$("#rightRows");host.innerHTML="";for(let i=0;i<5;i++){const row=i+11;const item=state[side][i];const cols=side==="left"?["1","2","3","4","5","6"]:["7","8","9","10","11","12"];for(let j=0;j<6;j++){if(side==="left"&&i===4&&j<2)continue;const el=document.createElement("div");el.className="product-cell"+(j===0?" left-edge":"")+(j===5?" right-edge":"")+(i===4?" last-left":"");el.style.gridColumn=cols[j];el.style.gridRow=(side==="left"&&i===3&&j<2)?"14 / 16":String(row);if(side==="left"&&i===3&&j<2)el.classList.add("merge-two");if(j===0){el.classList.add("sl-cell");el.textContent=String(i+1)}else if(j===5){el.classList.add("amt-cell");el.id=side+"Amt"+i;el.textContent=money(num(item.ctn)*num(item.rate))}else{const input=document.createElement("input");input.className="sheet-input";input.value=j===1?item.name:j===2?item.pack:j===3?item.ctn:j===4?item.rate:"";if(j===3||j===4){input.type="number";input.min="0";input.step="0.01"}input.dataset.side=side;input.dataset.i=i;input.dataset.field=j===1?"name":j===2?"pack":j===3?"ctn":"rate";input.addEventListener("input",()=>{state[side][i][input.dataset.field]=input.value;syncEditors();renderSheet();scheduleSave()});el.appendChild(input)}host.appendChild(el)}}}function syncPreviewFields(){ensureNumber();$("#pRef").value=state.ref;$("#pNo").value=String(state.invoiceNo).padStart(4,"0");$("#pDate").value=displayDate(state.date);$("#pRepName").value=state.repName;$("#pRepRole").value=state.repRole;$("#pRepMob").value=state.repMob;$("#pCommission").value=state.commission;$("#pWords").value=state.amountWords;const t=totals();$("#pLeftCartons").textContent=String(t.leftCtn);$("#pLeftAmount").textContent=money(t.leftAmount);$("#pRightAmount").textContent=money(t.rightAmount);$("#pTotalCartons").textContent=String(t.ctn);$("#pTotalTaka").textContent=money(t.totalTaka);$("#pTotalAmount").textContent=money(t.grand)}
function syncEditors(){ensureNumber();$("#ref").value=state.ref;$("#invoiceNo").value=String(state.invoiceNo).padStart(4,"0");$("#invoiceDate").value=state.date;$("#repName").value=state.repName;$("#repRole").value=state.repRole;$("#repMob").value=state.repMob;$("#commission").value=state.commission;$("#amountWords").value=state.amountWords}
function renderEditors(){syncEditors();makeProductEditor("left");makeProductEditor("right")}
function renderSheet(){buildRows("left");buildRows("right");syncPreviewFields()}
function syncAll(save=true){readStateFromEditor();renderSheet();if(save)scheduleSave();else $("#saveState").textContent="Saved locally"}
function bindSimple(id,pid){const a=$("#"+id),b=$("#"+pid);a.addEventListener("input",()=>{state[id==="invoiceNo"?"invoiceNo":id]=a.value; if(id==="commission")state.commission=Math.max(0,num(a.value)); renderSheet();scheduleSave()});b.addEventListener("input",()=>{state[id==="invoiceNo"?"invoiceNo":id]=b.value;if(id==="pCommission")state.commission=Math.max(0,num(b.value));renderEditors();renderSheet();scheduleSave()})}
function fillFromSheet(){state.ref=$("#pRef").value;state.invoiceNo=$("#pNo").value;state.date=parseDisplayDate($("#pDate").value);state.repName=$("#pRepName").value;state.repRole=$("#pRepRole").value;state.repMob=$("#pRepMob").value;state.commission=Math.max(0,num($("#pCommission").value));state.amountWords=$("#pWords").value}
function bindPreviewInputs(){["ref","invoiceNo","invoiceDate","repName","repRole","repMob","commission","amountWords"].forEach((id)=>{const map={ref:"pRef",invoiceNo:"pNo",invoiceDate:"pDate",repName:"pRepName",repRole:"pRepRole",repMob:"pRepMob",commission:"pCommission",amountWords:"pWords"};const a=$("#"+id),b=$("#"+map[id]);const f=()=>{state.ref=$("#ref").value.trim();state.invoiceNo=$("#invoiceNo").value.trim();state.date=$("#invoiceDate").value;state.repName=$("#repName").value;state.repRole=$("#repRole").value;state.repMob=$("#repMob").value;state.commission=Math.max(0,num($("#commission").value));state.amountWords=$("#amountWords").value;ensureNumber();$("#"+map[id]).value=id==="invoiceNo"?String(state.invoiceNo).padStart(4,"0"):a.value;scheduleSave()};a.addEventListener("input",f);b.addEventListener("input",()=>{fillFromSheet();renderEditors();renderSheet();scheduleSave()})})}
function saveRecord(){fillFromSheet();syncCounter(state.invoiceNo);const data=JSON.parse(JSON.stringify(state));if(!data.invoiceNo)data.invoiceNo=nextNo();const req=db.transaction("invoices","readwrite").objectStore("invoices").put({id:data.invoiceNo,invoiceNumber:data.invoiceNo,updatedAt:Date.now(),data,total:totals().grand});req.onsuccess=()=>{renderHistory();$("#saveState").textContent="Saved locally";toast("Invoice saved · "+data.invoiceNo)}}
function renderHistory(){if(!db)return;const host=$("#historyList"),req=db.transaction("invoices").objectStore("invoices").index("updatedAt").openCursor(null,"prev");host.innerHTML="";req.onsuccess=()=>{const c=req.result;if(!c)return;const a=c.value,row=document.createElement("div");row.className="history-row";row.innerHTML='<div class="history-main"><strong>'+esc(a.invoiceNumber)+'</strong><span>'+money(a.total)+'</span></div><div class="history-actions"><button type="button" class="load">Load</button><button type="button" class="copy">Copy</button><button type="button" class="delete">×</button></div>';row.querySelector(".load").onclick=()=>{Object.assign(state,JSON.parse(JSON.stringify(a.data)));renderEditors();renderSheet();toast("Invoice loaded · "+a.invoiceNumber)};row.querySelector(".copy").onclick=()=>{Object.assign(state,JSON.parse(JSON.stringify(a.data)));state.invoiceNo=nextNo();state.date=localDate();renderEditors();renderSheet();scheduleSave();toast("Copied as "+state.invoiceNo)};row.querySelector(".delete").onclick=()=>{if(confirm("Delete this saved invoice?")){db.transaction("invoices","readwrite").objectStore("invoices").delete(a.id).onsuccess=renderHistory}};host.appendChild(row);c.continue()}}
function newInvoice(){const oldCompany={repName:state.repName,repRole:state.repRole,repMob:state.repMob};Object.assign(state,{ref:"X2",invoiceNo:nextNo(),date:"",...oldCompany,commission:0,amountWords:"",left:Array.from({length:5},()=>({name:"",pack:"",ctn:"",rate:""})),right:Array.from({length:5},()=>({name:"",pack:"",ctn:"",rate:""}))});renderEditors();renderSheet();saveDraft();toast("New invoice · "+state.invoiceNo)}
function exportJSON(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="BNC-Invoice-"+(state.invoiceNo||"draft")+".json";a.click();URL.revokeObjectURL(u)}
function importJSON(file){file.text().then(t=>{const d=JSON.parse(t);if(!d||!Array.isArray(d.left)||!Array.isArray(d.right))throw Error("Invalid BNC invoice JSON");Object.assign(state,d);ensureNumber();renderEditors();renderSheet();scheduleSave();toast("Invoice imported")}).catch(()=>toast("Invalid invoice JSON"))}
function setupInstall(){const b=$("#installBtn");if(!b)return;addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;b.hidden=false});b.onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;b.hidden=true};addEventListener("appinstalled",()=>{b.hidden=true})}
function loadDraft(){return new Promise(resolve=>{if(!db)return resolve(false);const q=db.transaction("drafts").objectStore("drafts").get("current");q.onsuccess=()=>{if(q.result?.data){Object.assign(state,q.result.data);resolve(true)}else resolve(false)};q.onerror=()=>resolve(false)})}
(async()=>{try{await openDB();const loaded=await loadDraft();if(!loaded){ensureNumber()}renderEditors();renderSheet();bindPreviewInputs();$("#saveInvoice").onclick=saveRecord;$("#newInvoice").onclick=newInvoice;$("#printBtn").onclick=()=>{syncAll(false);saveRecord();window.print()};$("#jsonBtn").onclick=exportJSON;$("#importBtn").onclick=()=>$("#importFile").click();$("#importFile").onchange=e=>{const f=e.target.files?.[0];if(f)importJSON(f);e.target.value=""};setupInstall();renderHistory();}catch(e){toast("Local storage unavailable");renderEditors();renderSheet()}})();
})();