(() => {
"use strict";
const VID=0x258A,PID=0x010C,RID=0x06,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ROWS=[
[["Esc",0,1,"fn"],["F1",12,1,""],["F2",18,1,""],["F3",24,1,""],["F4",30,1,""],["F5",36,1,""],["F6",42,1,""],["F7",48,1,""],["F8",54,1,""],["F9",60,1,""],["F10",66,1,""],["F11",72,1,""],["F12",78,1,""],["Del",85,1,"nav"],["VOL",99,1,"knob"]],
[["~",1,1,""],["1",7,1,""],["2",13,1,""],["3",19,1,""],["4",25,1,""],["5",31,1,""],["6",37,1,""],["7",43,1,""],["8",49,1,""],["9",55,1,""],["0",61,1,""],["-",67,1,""],["=",73,1,""],["Backspace",79,2,"mod"],["PgUp",86,1,"nav"]],
[["Tab",2,1.5,"mod"],["Q",8,1,""],["W",14,1,""],["E",20,1,""],["R",26,1,""],["T",32,1,""],["Y",38,1,""],["U",44,1,""],["I",50,1,""],["O",56,1,""],["P",62,1,""],["[",68,1,""],["]",74,1,""],["\\",80,1.5,"mod"],["PgDn",87,1,"nav"]],
[["Caps",3,1.75,"mod"],["A",9,1,""],["S",15,1,""],["D",21,1,""],["F",27,1,""],["G",33,1,""],["H",39,1,""],["J",45,1,""],["K",51,1,""],["L",57,1,""],[";",63,1,""],["'",69,1,""],["Enter",81,2.25,"nav"],["PrtSc",84,1,"nav"]],
[["LShift",4,2.25,"mod"],["Z",10,1,""],["X",16,1,""],["C",22,1,""],["V",28,1,""],["B",34,1,""],["N",40,1,""],["M",46,1,""],[",",52,1,""],[".",58,1,""],["/",64,1,""],["RShift",70,1.75,"mod"],["Up",82,1,"nav"]],
[["LCtrl",5,1.25,"mod"],["Win",11,1.25,"mod"],["LAlt",17,1.25,"mod"],["Space",35,6.25,""],["RAlt",59,1.25,"mod"],["Fn",53,1.25,"fn"],["RCtrl",71,1.25,"mod"],["Left",77,1,"nav"],["Down",83,1,"nav"],["Right",89,1,"nav"]]];
const MAP={Escape:0,Backquote:1,Tab:2,CapsLock:3,ShiftLeft:4,ControlLeft:5,Digit1:7,KeyQ:8,KeyA:9,KeyZ:10,MetaLeft:11,F1:12,Digit2:13,KeyW:14,KeyS:15,KeyX:16,AltLeft:17,F2:18,Digit3:19,KeyE:20,KeyD:21,KeyC:22,F3:24,Digit4:25,KeyR:26,KeyF:27,KeyV:28,F4:30,Digit5:31,KeyT:32,KeyG:33,KeyB:34,Space:35,F5:36,Digit6:37,KeyY:38,KeyH:39,KeyN:40,F6:42,Digit7:43,KeyU:44,KeyJ:45,KeyM:46,F7:48,Digit8:49,KeyI:50,KeyK:51,Comma:52,F8:54,Digit9:55,KeyO:56,KeyL:57,Period:58,AltRight:59,F9:60,Digit0:61,KeyP:62,Semicolon:63,Slash:64,F10:66,Minus:67,BracketLeft:68,Quote:69,ShiftRight:70,ControlRight:71,F11:72,Equal:73,BracketRight:74,ArrowLeft:77,F12:78,Backspace:79,Backslash:80,Enter:81,ArrowUp:82,ArrowDown:83,PrintScreen:84,Delete:85,PageUp:86,PageDown:87,ArrowRight:89};
const NAME={Escape:"Esc",Backquote:"~",Tab:"Tab",CapsLock:"Caps",ShiftLeft:"LShift",ShiftRight:"RShift",ControlLeft:"LCtrl",ControlRight:"RCtrl",AltLeft:"LAlt",AltRight:"RAlt",MetaLeft:"Win",Enter:"Enter",Backspace:"Backspace",Space:"Space",ArrowLeft:"Left",ArrowDown:"Down",ArrowUp:"Up",ArrowRight:"Right",Delete:"Del",PageUp:"PgUp",PageDown:"PgDn",PrintScreen:"PrtSc",Backslash:"\\"};
const USAGES=[["A","0x04","Standard"],["B","0x05","Standard"],["C","0x06","Standard"],["D","0x07","Standard"],["E","0x08","Standard"],["F","0x09","Standard"],["G","0x0A","Standard"],["H","0x0B","Standard"],["I","0x0C","Standard"],["J","0x0D","Standard"],["K","0x0E","Standard"],["L","0x0F","Standard"],["M","0x10","Standard"],["N","0x11","Standard"],["O","0x12","Standard"],["P","0x13","Standard"],["Q","0x14","Standard"],["R","0x15","Standard"],["S","0x16","Standard"],["T","0x17","Standard"],["U","0x18","Standard"],["V","0x19","Standard"],["W","0x1A","Standard"],["X","0x1B","Standard"],["Y","0x1C","Standard"],["Z","0x1D","Standard"],["1","0x1E","Standard"],["2","0x1F","Standard"],["3","0x20","Standard"],["4","0x21","Standard"],["5","0x22","Standard"],["6","0x23","Standard"],["7","0x24","Standard"],["8","0x25","Standard"],["9","0x26","Standard"],["0","0x27","Standard"],["Enter","0x28","Standard"],["Esc","0x29","Standard"],["Backspace","0x2A","Standard"],["Tab","0x2B","Standard"],["Space","0x2C","Standard"],["-","0x2D","Standard"],["=","0x2E","Standard"],["[","0x2F","Standard"],["]","0x30","Standard"],["\\","0x31","Standard"],[";","0x33","Standard"],["'","0x34","Standard"],["\`","0x35","Standard"],[",","0x36","Standard"],[".","0x37","Standard"],["/","0x38","Standard"],["Caps","0x39","Standard"],["F1","0x3A","Function"],["F2","0x3B","Function"],["F3","0x3C","Function"],["F4","0x3D","Function"],["F5","0x3E","Function"],["F6","0x3F","Function"],["F7","0x40","Function"],["F8","0x41","Function"],["F9","0x42","Function"],["F10","0x43","Function"],["F11","0x44","Function"],["F12","0x45","Function"],["Print Screen","0x46","Navigation"],["Home","0x4A","Navigation"],["PgUp","0x4B","Navigation"],["Delete","0x4C","Navigation"],["End","0x4D","Navigation"],["PgDn","0x4E","Navigation"],["Right","0x4F","Navigation"],["Left","0x50","Navigation"],["Down","0x51","Navigation"],["Up","0x52","Navigation"],["Left Ctrl","0xE0","Modifier"],["Left Shift","0xE1","Modifier"],["Left Alt","0xE2","Modifier"],["Left Win","0xE3","Modifier"],["Right Ctrl","0xE4","Modifier"],["Right Shift","0xE5","Modifier"],["Right Alt","0xE6","Modifier"],["Right Win","0xE7","Modifier"],["Vol Up","0xE9","Media"],["Vol Down","0xEA","Media"],["Play/Pause","0xCD","Media"],["Next Track","0xB5","Media"],["Prev Track","0xB6","Media"],["Disabled","0x00","Special"],["Fn","0xFF","Special"]];
const PRESETS=[["Copy","Ctrl + C"],["Paste","Ctrl + V"],["Cut","Ctrl + X"],["Undo","Ctrl + Z"],["Redo","Ctrl + Shift + Z"],["Save","Ctrl + S"],["Select All","Ctrl + A"],["Find","Ctrl + F"],["New Tab","Ctrl + T"],["Close Tab","Ctrl + W"],["Refresh","Ctrl + R"],["Screenshot","Win + Shift + S"],["Task Manager","Ctrl + Shift + Esc"],["Lock Screen","Win + L"],["File Explorer","Win + E"],["Run Dialog","Win + R"],["Alt + F4","Alt + F4"],["Alt + Tab","Alt + Tab"]];
const EFFECTS=[[0,"Off"],[1,"Static"],[2,"Breathing"],[3,"Wave"],[4,"Spectrum"],[5,"Ripple"],[6,"Reactive"],[7,"Starlight"],[8,"Rain"],[9,"Snake"],[10,"Marquee"],[11,"Aurora"],[12,"Laser"],[13,"Firework"],[14,"Gradient"],[15,"Rainbow Wave"],[16,"Prism"],[17,"Cycle"],[18,"Tidal"],[21,"Custom"]];
function numSetting(key,fallback){const v=localStorage.getItem(key);const n=Number(v);return v!==null&&Number.isFinite(n)?n:fallback;}
const S={device:null,lastRaw:null,lastConfig:null,selected:null,held:new Set(),history:[],mappings:readMap(),mode:"single",category:"All",usage:"A",mods:new Set(),rgb:{color:localStorage.getItem("f75pro:rgb:color")||"#6d8dff",brightness:numSetting("f75pro:rgb:brightness",7),speed:numSetting("f75pro:rgb:speed",2),effect:numSetting("f75pro:rgb:effect",1)}};
function readMap(){try{const x=JSON.parse(localStorage.getItem("f75pro:mappings")||"{}");return x&&typeof x==="object"&&!Array.isArray(x)?x:{};}catch{return {};}}
function saveMap(){localStorage.setItem("f75pro:mappings",JSON.stringify(S.mappings));renderKeys();syncEditor();}
function log(x){const e=$("#eventLog");e.textContent+="\\n["+new Date().toLocaleTimeString()+"] "+x;e.scrollTop=e.scrollHeight;}
function hex(a){return [...a].map(x=>x.toString(16).padStart(2,"0")).join(" ");}
function dl(n,d,t){const b=new Blob([d],{type:t}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function keyLabel(i){const x=ROWS.flat().find(k=>k[1]===i);return x?x[0]+" (#"+i+")":"Matrix #"+i;}
function fname(c){return NAME[c]||(c.startsWith("Key")?c.slice(3).toUpperCase():c.startsWith("Digit")?c.slice(5):c);}
function renderKeys(){const h=$("#keyboard");h.innerHTML="";ROWS.forEach(row=>{const r=document.createElement("div");r.className="krow";row.forEach(([l,i,w,k])=>{const b=document.createElement("button");b.className="key"+(k==="knob"?" knob":"");b.style.width=(w*50+Math.max(0,w-1)*5)+"px";b.dataset.matrix=i;b.innerHTML='<span class="lab"></span><span class="idx">#'+i+"</span>";b.querySelector(".lab").textContent=l;if(S.selected===i)b.classList.add("selected");if(S.mappings[i]){const m=document.createElement("span");m.className="map";m.textContent="→ "+S.mappings[i];b.appendChild(m);}b.onclick=()=>select(i,l);b.ondblclick=e=>{e.preventDefault();test(i,l)};r.appendChild(b);});h.appendChild(r);});$("#mappedCount").textContent=Object.keys(S.mappings).length+" mapped";}
function select(i,l){S.selected=i;renderKeys();$("#selectedBadge").textContent="matrix #"+i;$("#selectedLabel").textContent=l+" · matrix #"+i+(S.mappings[i]?" → "+S.mappings[i]:"");$("#glowKey").textContent=l;syncEditor();}
function syncEditor(){const i=S.selected;$("#editorCount").textContent=Object.keys(S.mappings).length+" mapped";if(i===null){$("#editorStatus").textContent="Select a physical key, then choose an output.";return;}const v=S.mappings[i]||"";if(v&&USAGES.some(u=>u[0]===v)){S.usage=v;renderUsage();}$("#editorStatus").textContent=v?"Current mapping: "+keyLabel(i)+" → "+v:"No local mapping for "+keyLabel(i)+".";}
function flash(i,ms=220){const e=$("#keyboard [data-matrix='"+i+"']");if(!e)return;e.classList.add("live");clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove("live"),ms);}
function hist(x){S.history.unshift(x);S.history=S.history.slice(0,8);$("#liveHistory").innerHTML=S.history.map(v=>'<span class="chip">'+v+"</span>").join("");}
function down(c,src){if(S.held.has(c))return;S.held.add(c);const i=MAP[c],n=fname(c);if(i!==undefined)flash(i,280);$("#liveCurrent").textContent=[...S.held].map(fname).join(" + ");$("#liveMeta").textContent=n+(i===undefined?"":" · matrix #"+i)+(i!==undefined&&S.mappings[i]?" · mapped → "+S.mappings[i]:"");$("#liveSource").textContent=src;$("#heldCount").textContent=S.held.size+" held";hist(n);log(src+": "+n+(i===undefined?"":" · matrix #"+i));}
function up(c){S.held.delete(c);$("#heldCount").textContent=S.held.size+" held";if(!S.held.size)$("#liveCurrent").textContent=S.history.length?"No keys held":"Press a key on your keyboard…";}
function test(i,l){flash(i,320);$("#liveSource").textContent="Virtual test input";$("#liveCurrent").textContent=l;$("#liveMeta").textContent=l+" · matrix #"+i;hist(l);}
addEventListener("keydown",e=>{const t=e.target;if(t&&((t.tagName==="INPUT"&&t.type!=="color")||t.tagName==="TEXTAREA"||t.tagName==="SELECT"||t.isContentEditable))return;if(e.repeat)return;if(MAP[e.code]!==undefined)down(e.code,"OS keyboard events");},true);
addEventListener("keyup",e=>up(e.code),true);addEventListener("blur",()=>{S.held.clear();$("#heldCount").textContent="0 held";});
function probePacket(c){const a=new Uint8Array(519);a[0]=c;a[1]=0;a[2]=0;a[3]=1;a[4]=0;a[5]=0;a[6]=c===0x84?0x80:0;return a;}
function demoPacket(c){const a=new Uint8Array(519);a[0]=RID;a[1]=c;a[2]=1;a[3]=0;a[4]=1;a[5]=0;a[6]=128;for(let i=7;i<519;i++)a[i]=(i*37+c*11)%256;a[17]=0;a[18]=S.rgb.effect;a[26]=1;a[36]=100;for(let i=0;i<22;i++){const o=64+i*2;a[o]=S.rgb.brightness;a[o+1]=(S.rgb.speed&15)<<4;}return a;}
async function attach(d){try{if(!d.opened)await d.open();S.device=d;window.__f75Device=d;$("#statusDot").className="statusDot ok";$("#statusText").textContent="CONNECTED · WebHID";$("#usbId").textContent=d.vendorId.toString(16).padStart(4,"0")+":"+d.productId.toString(16).padStart(4,"0");$("#transport").textContent="WebHID / wired";$("#deviceName").textContent=d.productName||"AULA F75 Pro";$("#vendor").textContent="0x"+d.vendorId.toString(16).toUpperCase();$("#product").textContent="0x"+d.productId.toString(16).toUpperCase();$("#productName").textContent=d.productName||"AULA F75 Pro";$("#mode").textContent="connected hardware";$("#writeBadge").className="badge ok";$("#writeBadge").textContent="read-only hardware";observe(d);log("connected: "+(d.productName||"AULA F75"));}catch(e){log("connect error: "+e.message);}}
function disconnect(){const d=S.device;if(d&&d.opened)d.close().catch(()=>{});S.device=null;window.__f75Device=null;$("#statusDot").className="statusDot live";$("#statusText").textContent="LIVE DEMO · no keyboard";$("#usbId").textContent="258a:010c · simulated";$("#transport").textContent="Offline simulation";$("#deviceName").textContent="AULA F75 Pro · virtual";$("#vendor").textContent="0x258A";$("#product").textContent="0x010C";$("#productName").textContent="AULA F75 Pro · Virtual Device";$("#mode").textContent="offline live demo";$("#writeBadge").className="badge live";$("#writeBadge").textContent="simulation";}
async function connect(){if(!("hid"in navigator)){log("WebHID unavailable; offline mode remains active.");return;}try{const l=await navigator.hid.requestDevice({filters:[{vendorId:VID,productId:PID}]});if(l.length)await attach(l[0]);}catch(e){log("request cancelled: "+e.message);}}
async function transact(c){if(!S.device){await new Promise(r=>setTimeout(r,60));return demoPacket(c);}await S.device.sendFeatureReport(RID,probePacket(c));await new Promise(r=>setTimeout(r,45));return new Uint8Array((await S.device.receiveFeatureReport(RID)).buffer);}
async function runProbe(c){try{const b=await transact(c);S.lastRaw=b;if(c===0x84)S.lastConfig=b;$("#reportSize").textContent=b.length+" B";$("#reportOut").textContent="0x06";$("#reportTransport").textContent=S.device?"WebHID":"offline simulation";$("#reportEvent").textContent="0x"+c.toString(16);$("#rawConsole").textContent="command 0x"+c.toString(16)+"\\n"+hex(b);log((S.device?"hardware":"offline")+" probe 0x"+c.toString(16)+" · "+b.length+" bytes");if(c===0x84)decode();}catch(e){$("#rawConsole").textContent="Probe failed: "+e.message;}}
function decode(){if(!S.lastConfig){$("#decoded").textContent="No configuration report.";return;}const b=S.lastConfig,s=Math.max(0,b.length-128),p=b.slice(s,s+128),lines=["payload window: "+s+" → "+(s+p.length-1),"effect byte: "+(p[18]??0),"custom flag: "+(p[17]??0),"side-light byte: "+(p[26]??0),"battery byte: "+(p[36]??0),""];for(let i=0;i<22;i++){const o=64+i*2;if(o+1<p.length)lines.push("effect "+i+": brightness="+p[o]+" params=0x"+p[o+1].toString(16).padStart(2,"0"));}$("#decoded").textContent=lines.join("\\n");}
function observe(d){if(d.__f75Observed)return;d.__f75Observed=true;try{d.addEventListener("inputreport",e=>{const b=new Uint8Array(e.data.buffer,e.data.byteOffset,e.data.byteLength);$("#liveSource").textContent="WebHID input report + OS events";$("#liveMeta").textContent="report 0x"+Number(e.reportId).toString(16).padStart(2,"0")+" · "+hex(b);$("#reportSize").textContent=b.length+" B";$("#reportOut").textContent="0x"+Number(e.reportId).toString(16).padStart(2,"0");$("#reportTransport").textContent="WebHID";$("#reportEvent").textContent="input report";if(!S.held.size)$("#liveCurrent").textContent="HID activity detected";});}catch{}}
navigator.hid?.addEventListener("connect",e=>{if(e.device.vendorId===VID&&e.device.productId===PID)attach(e.device);});navigator.hid?.addEventListener("disconnect",e=>{if(S.device===e.device){log("keyboard disconnected; returning to offline mode.");disconnect();}});navigator.hid?.getDevices?.().then(l=>{const d=l.find(x=>x.vendorId===VID&&x.productId===PID);if(d)attach(d);}).catch(()=>{});
function show(id){$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$(".tab").forEach(v=>v.classList.toggle("active",v.dataset.tab===id));$$(".navBtn").forEach(v=>v.classList.toggle("active",v.dataset.view===id));}
$$(".navBtn").forEach(b=>b.onclick=()=>show(b.dataset.view));$$(".tab").forEach(b=>b.onclick=()=>show(b.dataset.tab));

const cats=["All","Standard","Function","Navigation","Modifier","Media","Special"];cats.forEach(c=>{const b=document.createElement("button");b.textContent=c;b.className=c==="All"?"active":"";b.onclick=()=>{S.category=c;$("#catHost").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));renderUsage();};$("#catHost").appendChild(b);});
function renderUsage(){const q=$("#usageSearch").value.trim().toLowerCase(),g=$("#usageGrid");g.innerHTML="";USAGES.filter(u=>(S.category==="All"||u[2]===S.category)&&(u[0].toLowerCase().includes(q)||u[1].toLowerCase().includes(q))).forEach(u=>{const b=document.createElement("button");b.className="usage"+(S.usage===u[0]?" selected":"");b.innerHTML="<b></b><small></small>";b.querySelector("b").textContent=u[0];b.querySelector("small").textContent=u[1];b.onclick=()=>{S.usage=u[0];renderUsage();$("#editorStatus").textContent="Selected output: "+u[0]+" ("+u[1]+")";};g.appendChild(b);});}
$("#usageSearch").oninput=renderUsage;USAGES.filter(u=>!["Modifier","Special"].includes(u[2])).forEach(u=>{const o=document.createElement("option");o.value=u[0];o.textContent=u[0]+" ("+u[1]+")";$("#comboKey").appendChild(o);});
function comboPreview(){const x=[...S.mods,$("#comboKey").value];$("#comboPreview").textContent="Shortcut: "+x.join(" + ");}$$(".mods button").forEach(b=>b.onclick=()=>{const m=b.dataset.mod;S.mods.has(m)?S.mods.delete(m):S.mods.add(m);b.classList.toggle("active",S.mods.has(m));comboPreview();});$("#comboKey").onchange=comboPreview;
$$(".editortabs button").forEach(b=>b.onclick=()=>{S.mode=b.dataset.mode;$$(".editortabs button").forEach(x=>x.classList.toggle("active",x===b));$("#modeSingle").hidden=S.mode!=="single";$("#modeCombo").hidden=S.mode!=="combo";$("#modePreset").hidden=S.mode!=="preset";});
PRESETS.forEach(([n,v])=>{const b=document.createElement("button");b.className="preset";b.dataset.value=v;b.innerHTML="<b></b><small></small>";b.querySelector("b").textContent=n;b.querySelector("small").textContent=v;b.onclick=()=>{$$("#presetGrid .preset").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("#editorStatus").textContent="Selected preset: "+v;};$("#presetGrid").appendChild(b);});
function editorValue(){if(S.mode==="combo")return $("#comboPreview").textContent.replace(/^Shortcut: /,"");if(S.mode==="preset")return $("#presetGrid .selected")?.dataset.value||"";return S.usage;}
$("#addMap").onclick=()=>{if(S.selected===null){$("#editorStatus").textContent="Select a physical key first.";return;}const v=editorValue();if(!v)return;if(S.mappings[S.selected]!==undefined){$("#editorStatus").textContent="Mapping already exists. Use Edit.";return;}S.mappings[S.selected]=v;saveMap();$("#editorStatus").textContent="Added "+keyLabel(S.selected)+" → "+v;};
$("#editMap").onclick=()=>{if(S.selected===null){$("#editorStatus").textContent="Select a physical key first.";return;}if(S.mappings[S.selected]===undefined){$("#editorStatus").textContent="No existing mapping. Use Add / Apply.";return;}const v=editorValue();if(!v)return;S.mappings[S.selected]=v;saveMap();$("#editorStatus").textContent="Edited "+keyLabel(S.selected)+" → "+v;};
$("#deleteMap").onclick=()=>{if(S.selected===null)return;if(S.mappings[S.selected]===undefined){$("#editorStatus").textContent="Nothing to delete.";return;}delete S.mappings[S.selected];saveMap();$("#editorStatus").textContent="Deleted mapping for "+keyLabel(S.selected);};
$("#resetSelected").onclick=()=>{if(S.selected===null)return;delete S.mappings[S.selected];saveMap();$("#editorStatus").textContent="Reset selected key.";};
$("#resetAll").onclick=()=>{if(!confirm("Reset every local key mapping?"))return;S.mappings={};saveMap();$("#editorStatus").textContent="All local mappings reset.";};
$("#swapWinAlt").onclick=()=>{const a=S.mappings[11],b=S.mappings[17];S.mappings[11]=b===undefined?"Alt":b;S.mappings[17]=a===undefined?"Win":a;saveMap();$("#editorStatus").textContent="Local Win ↔ Alt mapping swapped.";};
$("#exportMap").onclick=()=>dl("f75-pro-keymap.json",JSON.stringify({format:"f75-pro-control-deck/5",mappings:S.mappings},null,2),"application/json");
$("#importMap").onclick=()=>{const i=document.createElement("input");i.type="file";i.accept=".json,application/json";i.onchange=async()=>{const f=i.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text()),o=p?.mappings&&typeof p.mappings==="object"?p.mappings:p,c={};Object.entries(o||{}).forEach(([k,v])=>{const n=Number(k);if(Number.isInteger(n)&&n>=0&&n<=127&&typeof v==="string"&&v.trim())c[n]=v.trim();});S.mappings=c;saveMap();$("#editorStatus").textContent="Imported "+Object.keys(c).length+" mappings.";}catch(e){$("#editorStatus").textContent="Import failed: "+e.message;}};i.click();};

EFFECTS.forEach(([id,n])=>{const b=document.createElement("button");b.className="effect"+(id===S.rgb.effect?" selected":"");b.textContent=id+" · "+n;b.onclick=()=>{S.rgb.effect=id;localStorage.setItem("f75pro:rgb:effect",id);$$("#effectGrid .effect").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");rgbLabels();};$("#effectGrid").appendChild(b);});
for(let i=0;i<75;i++){const p=document.createElement("span");p.className="led";$("#leds").appendChild(p);}$("#rgbColor").value=S.rgb.color;$("#brightness").value=S.rgb.brightness;$("#speed").value=S.rgb.speed;
function rgbLabels(){const n=(EFFECTS.find(x=>x[0]===S.rgb.effect)||[0,"Custom"])[1];$("#rgbHex").textContent=S.rgb.color.toUpperCase();$("#brightnessOut").textContent=S.rgb.brightness;$("#speedOut").textContent=S.rgb.speed;$("#effectCaption").textContent=n+" · "+S.rgb.color.toUpperCase();$("#rgbStage").style.setProperty("--rgb",S.rgb.color+"88");}
$("#rgbColor").oninput=e=>{S.rgb.color=e.target.value;localStorage.setItem("f75pro:rgb:color",S.rgb.color);rgbLabels();};$("#brightness").oninput=e=>{S.rgb.brightness=+e.target.value;localStorage.setItem("f75pro:rgb:brightness",S.rgb.brightness);rgbLabels();};$("#speed").oninput=e=>{S.rgb.speed=+e.target.value;localStorage.setItem("f75pro:rgb:speed",S.rgb.speed);rgbLabels();};$("#previewRgb").onclick=rgbLabels;
requestAnimationFrame(function loop(t){const sp=Math.max(1,S.rgb.speed),br=Math.max(.08,S.rgb.brightness/9);[...$("#leds").children].forEach((p,i)=>{let v=.55,e=S.rgb.effect;if(e===0)v=0;else if(e===1)v=1;else if(e===2)v=.45+.35*(.5+.5*Math.sin(t/520*sp));else if(e===3)v=.2+.8*(.5+.5*Math.sin(t/150*sp+i*.22));else if(e===5)v=.12+.88*Math.max(0,Math.sin(t/260*sp+i*.55));else if(e===8)v=.12+.88*(((i*7+Math.floor(t/90*sp))%75)/74);else v=.3+.7*(.5+.5*Math.sin(t/280*sp+i*.17));p.style.background=S.rgb.color;p.style.opacity=Math.min(1,v*br);p.style.boxShadow="0 0 11px "+S.rgb.color+"55";});requestAnimationFrame(loop);});
$("#applyRgb").onclick=()=>{localStorage.setItem("f75pro:demo-rgb",JSON.stringify(S.rgb));if(!S.device){$("#writeBadge").className="badge live";$("#writeBadge").textContent="simulation write";log("offline RGB state applied locally.");return;}alert("Persistent hardware RGB writes remain gated. No hardware bytes were written.");};

$("#connectBtn").onclick=connect;$("#disconnectBtn").onclick=disconnect;$("#probeBtn").onclick=()=>runProbe(0x82);$("#readConfigBtn").onclick=()=>runProbe(0x84);$("#rawRead").onclick=()=>runProbe(parseInt($("#commandSelect").value,16));$("#decodeLast").onclick=decode;
$("#saveSnapshotBtn").onclick=saveSnapshot;$("#backupBtn").onclick=saveSnapshot;
function saveSnapshot(){if(!S.lastRaw&&!S.lastConfig){alert("Run a probe first.");return;}const p={createdAt:new Date().toISOString(),connected:!!S.device,device:S.device?{vendorId:S.device.vendorId,productId:S.device.productId,productName:S.device.productName}:null,raw:S.lastRaw?[...S.lastRaw]:null,config:S.lastConfig?[...S.lastConfig]:null,mappings:S.mappings,rgb:S.rgb};dl("f75-pro-session-"+Date.now()+".json",JSON.stringify(p,null,2),"application/json");}
$("#clearLogs").onclick=()=>$("#eventLog").textContent="Event log cleared.";
$("#clearAllLocal").onclick=()=>{if(!confirm("Clear all F75 PRO local state?"))return;Object.keys(localStorage).filter(k=>k.startsWith("f75pro:")).forEach(k=>localStorage.removeItem(k));S.mappings={};S.rgb={color:"#6d8dff",brightness:7,speed:2,effect:1};renderKeys();rgbLabels();$("#editorStatus").textContent="All local state cleared.";};
$("#support").textContent="WebHID: "+("hid"in navigator?"available":"unavailable")+" · LIVE DEMO stays available without a device.";

renderKeys();renderUsage();comboPreview();rgbLabels();syncEditor();
})();